import { matchPath } from 'react-router-dom';

// Route chunks load on demand (see router/config.tsx lazy() imports), so the
// first navigation to a page pays for its download. Fetching that chunk while
// the pointer is still travelling toward the link usually hides the cost, so
// the Suspense fallback never appears.
//
// This map is intentionally self-contained rather than exported from
// config.tsx: that file is regenerated by the Readdy builder, and importing
// from it would couple this to a structure we do not control. The import
// specifiers below are identical to the lazy() calls in config.tsx, and both
// files sit in src/router/, so each import() here warms exactly the chunk the
// matching route will later request. Keep this list in step with the public
// routes in config.tsx; a missing entry simply means no prefetch for that
// route, never a broken link.

type Loader = () => Promise<unknown>;

const ROUTES: ReadonlyArray<readonly [string, Loader]> = [
  ['/', () => import('../pages/home/page')],
  ['/buy', () => import('../pages/Buy')],
  ['/rent', () => import('../pages/Rent')],
  ['/all-properties', () => import('../pages/AllProperties')],
  ['/landlords', () => import('../pages/Landlords')],
  ['/neighbourhoods', () => import('../pages/Neighbourhoods')],
  ['/neighbourhood/:slug', () => import('../pages/NeighbourhoodDetail')],
  ['/blog/:slug', () => import('../pages/BlogDetail')],
  ['/new-developments', () => import('../pages/NewDevelopments')],
  ['/joint-ventures', () => import('../pages/JointVentures')],
  ['/joint-ventures/project/:slug', () => import('../pages/JointVentureProjectDetail')],
  ['/about', () => import('../pages/About')],
  ['/contact', () => import('../pages/Contact')],
  ['/valuation', () => import('../pages/Valuation')],
  ['/property/:slug', () => import('../pages/PropertyDetail')],
  ['/commercial-property', () => import('../pages/CommercialProperty')],
  ['/commute-time', () => import('../pages/CommuteTime')],
  ['/schools', () => import('../pages/Schools')],
];

const requested = new Set<Loader>();

/** Warm the chunk for a pathname, if it maps to a known public route. */
export function prefetchPath(pathname: string): void {
  for (const [pattern, load] of ROUTES) {
    if (!matchPath({ path: pattern, end: true }, pathname)) continue;
    if (requested.has(load)) return;
    requested.add(load);
    load().catch(() => { requested.delete(load); });
    return;
  }
}

// Respect data-saver and very slow links: a wasted chunk costs more there than
// the latency it would save.
function prefetchingIsWelcome(): boolean {
  const conn = (navigator as Navigator & {
    connection?: { saveData?: boolean; effectiveType?: string };
  }).connection;
  if (!conn) return true;
  if (conn.saveData) return false;
  return conn.effectiveType !== 'slow-2g' && conn.effectiveType !== '2g';
}

function toRoutePath(url: URL, basename: string): string | null {
  if (url.origin !== window.location.origin) return null;
  let path = url.pathname;
  if (basename && basename !== '/') {
    if (!path.startsWith(basename)) return null;
    path = path.slice(basename.length) || '/';
  }
  return path.startsWith('/') ? path : `/${path}`;
}

/**
 * Install one delegated listener that prefetches a route's chunk on hover or
 * keyboard focus of a link to it. One listener covers every <Link> in the app,
 * so no call site needs to opt in. Returns a cleanup function.
 */
export function installRoutePrefetch(basename = '/'): () => void {
  if (!prefetchingIsWelcome()) return () => {};

  const onCandidate = (event: Event) => {
    const target = event.target;
    if (!(target instanceof Element)) return;
    const anchor = target.closest('a[href]');
    if (!anchor) return;

    const href = anchor.getAttribute('href');
    if (!href || href.startsWith('#')) return;
    if (anchor.hasAttribute('download')) return;
    const targetAttr = anchor.getAttribute('target');
    if (targetAttr && targetAttr !== '_self') return;

    let url: URL;
    try { url = new URL(href, window.location.href); } catch { return; }
    if (url.protocol !== 'http:' && url.protocol !== 'https:') return;

    const path = toRoutePath(url, basename);
    if (path) prefetchPath(path);
  };

  // pointerover delegates (pointerenter does not bubble); focusin covers
  // keyboard navigation.
  document.addEventListener('pointerover', onCandidate, { passive: true });
  document.addEventListener('focusin', onCandidate, { passive: true });

  return () => {
    document.removeEventListener('pointerover', onCandidate);
    document.removeEventListener('focusin', onCandidate);
  };
}
